### ISSUE TITLE
Cannot "Open Windows Terminal Here" on a drive root

### ISSUE THREAD

**Issue by jeremyVignelles** [shanselman/WindowsTerminalHere#4]
Hi,
Thanks for the file and the blog post, I'll be using wt everyday now 😄 

Now, when I right click on a drive from "This PC" and select "Open Windows Terminal Here", I get this:

```
[error 0x8007010b when launching `powershell.exe']
```

Did I do something wrong? 

Please note that I downloaded the .inf from #3 instead of the master one, because I wanted to right click inside a folder. When I do it inside, the issue is still the same, but it works fine on other folders.

**Comment by etheralm** [comment]
you can fix it by opening regedit and changing in `Computer\HKEY_CLASSES_ROOT\Drive\shell\WindowsTerminalHere\command`
`"%1"` to `"%1\"`
to fix the background right click in a drive root (the addition from the pull request) you have to change in `Computer\HKEY_CLASSES_ROOT\Directory\Background\shell\WindowsTerminalHere\command`
`"%V"` to `"%V\."`

you can find more info about this issue here: https://github.com/microsoft/terminal/issues/4571

cheers

**Comment by chungweileong94** [comment]
I'm already fixed in my [fork](https://github.com/chungweileong94/WindowsTerminalHere), thanks to the info from @etheralm 

However, I did modify something in my fork to fit my own preference, so I'm not sure if I wanted to create a PR for this. Here are the changes I made:
- Change the "Windows Terminal Here" label to "Open Windows Terminal Here"
- Added "Open Windows Terminal Here" to directory background
- Fixed "Open Windows Terminal Here" on drive root

**Comment by shanselman** [comment]
Cool @chungweileong94! Send it over!

**Comment by chungweileong94** [comment]
@shanselman Sorry for the double PR, I'm still new to the GitHub world

**Comment by jawn** [comment]
> @shanselman Sorry for the double PR, I'm still new to the GitHub world

Hey @chungweileong94 , thanks for [getting involved](https://getinvolved.hanselman.com/) 🚀 and improving open source software!

**Comment by LinuxOnTheDesktop** [comment]
> you can fix it by opening regedit and changing in Computer\HKEY_CLASSES_ROOT\Drive\shell\WindowsTerminalHere\command
> "%1" to "%1\"

I do not have that key on my system (Windows 10 Pro - 21H2 (2009: 19044)). Nor does https://github.com/microsoft/terminal/issues/4571 seem to shed light on just what keys and values one should create.
